version: '3.7'

services:

  craft-vue:
    container_name: craft-dashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:80'
